name: money_console
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-85.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_riverpod: ^1.0.3
  tuple: ^2.0.0
  flutter_calendar_carousel: ^2.1.0
  http: ^0.13.4
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  syncfusion_flutter_charts: ^20.1.50
  font_awesome_flutter: ^10.1.0
  scrollable_positioned_list: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  build_runner: ^2.1.8
  freezed: ^1.1.1
  json_serializable: ^6.1.5

flutter:

  uses-material-design: true
